In [2]:
import numpy as np
from scipy import linalg

In [3]:
testQuestionVariable=np.array([[1,1],[4,9]])
testQuestionValue=np.array([30,150])


In [4]:
linalg.solve(testQuestionVariable,testQuestionValue)

array([24.,  6.])

In [5]:
from scipy.stats import norm

In [6]:
norm.rvs(loc=0,scale=1,size=20)

array([-0.88669429, -0.07882796,  1.5183496 , -1.27892133,  1.22133506,
       -0.63628264, -0.03894663, -1.33179665, -0.7122816 ,  0.53883707,
        0.80462629,  0.74898362,  2.16850222, -1.17803924, -0.51058479,
       -0.64336033, -1.5143416 , -0.14238921, -0.45594855,  1.07113313])

In [7]:
norm.cdf(10,loc=1,scale=3)

0.9986501019683699

In [8]:
norm.pdf(14,loc=1,scale=1)

7.998827757006813e-38

In [9]:
matrix=np.array([[4,9],[3,5]])
matrix

array([[4, 9],
       [3, 5]])

In [11]:
type(matrix)

numpy.ndarray

In [10]:
linalg.det(matrix)

-7.000000000000001

In [12]:
linalg.inv(matrix)

array([[-0.71428571,  1.28571429],
       [ 0.42857143, -0.57142857]])

In [13]:
matrix.shape

(2, 2)

In [14]:
#svd function(single value decomposition)
linalg.svd(matrix)

(array([[-0.86130311, -0.50809147],
        [-0.50809147,  0.86130311]]),
 array([11.4291242 ,  0.61247038]),
 array([[-0.43480907, -0.90052267],
        [ 0.90052267, -0.43480907]]))

In [15]:
#How to perform quad integration
from scipy.integrate import quad

In [16]:
def integratefunction(x):
    return x

In [17]:
quad(integratefunction,0,1)

(0.5, 5.551115123125783e-15)

In [18]:
def integratefn(x,a,b):
    return x*a+b

In [19]:
a=3
b=2

In [20]:
quad(integratefn,0,1,args=(a,b))

(3.5, 3.885780586188048e-14)

In [22]:
import scipy.integrate as integrate 
def f(x,y):
    return x+y
integrate.dblquad(f,0,1,lambda x:0,lambda x:2)

(3.0, 4.436070580899685e-14)